# Generated by Django 4.1.1 on 2022-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
