# Generated by Django 4.1.1 on 2022-09-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_data_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
